version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: /home/circleci/project
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
        name: List directory contents
        command: ls -la /home/circleci/project/



