version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14  # Utiliza una imagen de Node.js 14

    working_directory: /main/circleci/project  # Cambia el directorio de trabajo a uno predeterminado

    steps:
      - checkout  # Clona el código del repositorio

      - run:
          name: Install dependencies
          command: npm install  # Instala las dependencias del proyecto

      - run:
          name: Run tests
          command: npm test  # Ejecuta los tests del proyecto

